#!/bin/bash

PYTHON=python3.9
# CHECK PYTHON 3
if command -v $PYTHON &>/dev/null; then
    echo Python3 available
else
    echo Python3 not available, please install it or add to the PATH variable
    exit 1
fi

# CHECK PIP
if command -v $PYTHON -m pip &>/dev/null; then
    echo Pip available
else
    echo Pip not available, please install it or add to the PATH variable
    exit 1
fi

# CHECK VIRTUALENV COMMAND
if command -v $PYTHON -m venv &>/dev/null; then
    echo Venv command available
else
    echo Venv not available, please install it [For example: python3 -m pip install python-venv]
    exit 1
fi


COMMAND=$1
PYTHON_VERSION=3.9
while [[ "$#" -gt 0 ]]; do
    case $1 in
    --python-version)
        PYTHON_VERSION="$2"
        shift
        shift
        ;;
    *)
        COMMAND=$1
        shift
        break
        ;;
    esac
    shift
done
# CHECK VENV NOT EXISTS
if [ ! -d .venv ]; then

    $PYTHON -m venv .venv || exit 1
    if [ ! -d .pip ]; then
        mkdir .pip
        curl https://bootstrap.pypa.io/get-pip.py -o .pip/get-pip.py || exit 1
    fi
    .venv/bin/python3 .pip/get-pip.py || exit 1
    .venv/bin/pip3 install -r requirements.txt || exit 1
    .venv/bin/pip3 install -r requirements-tests.txt || exit 1
    .venv/bin/pip3 install -r requirements-dev.txt || exit 1
fi

if [ -f '.buildew' ]; then
    echo Use .buildew file to read sensitive information
    cat '.buildew' > '.buildew.tmp'
    echo "" >> '.buildew.tmp'
    while read -r LINE; do
        eval $LINE
    done <'.buildew.tmp'
    rm -fr '.buildew.tmp'
else
    # REGENERATE SENSITIVE INFO FROM TEMPLATE
    cat >'.buildew' <<EOF
AWS_ACCOUNT=1234567890.dkr.ecr.us-east-x.amazonaws.com
AWS_PROFILE=devops.user
AWS_REGION=us-east-x
AWS_HOSTED_ZONE_ID=Z00000000000000000000
AWS_DNS_RECORD_START=www
google_service_account=<service account from google developer console>
google_private_key_json=<private key JSON which downloaded from google cloud console>
EOF
fi


echo EXECUTE
echo =========== $COMMAND
echo $COMMAND ===========
echo COMMAND

function docker_build {
    echo "Build docker image $1"
    mkdir -p .prebuild
    cp -fr ~/.demo1 .prebuild
    cp -fr ~/.ssl/zefshar.com.zip .prebuild/.demo1/
    cp -fr .private/* .prebuild/.demo1/
    docker build --build-arg google_service_account="${google_service_account}" --build-arg google_private_key_json="${google_private_key_json}" -t $1 .
    rm -fr .prebuild
}

function build {
    CURRENT_FOLDER=$PWD
    cd demo1-frontend
    flutter build web --web-renderer html --release
    cd $CURRENT_FOLDER
    tar -cf demo1.flutter -C demo1-frontend/build/web .

    cd pr1
    flutter build web --web-renderer canvaskit --release
    cd $CURRENT_FOLDER
    tar -cf pr1.flutter -C pr1/build/web .

    docker_build 'demo1/demo1:v1'

}


if [ "x$COMMAND" == "xbuild" ]; then
    build
fi

if [ "x$COMMAND" == "xdev" ]; then
    echo 'Start application for development'
    CURRENT_FOLDER=$PWD
    ps -Fe | grep demo1.api.demo1 | awk ' { print $2 } ' | xargs kill -9
    $(.venv/bin/python3 -m demo1.api.demo1 -p 8080 || exit 1) &
    cd $CURRENT_FOLDER
    cd demo1
    flutter build web || exit 1
    flutter run -d chrome --web-hostname localhost --web-port 43433
    cd $CURRENT_FOLDER
fi

if [ "x$COMMAND" == "xrun" ]; then
    echo 'Run docker image'
    docker container stop demo1
    docker container rm demo1
    docker run -p 443 -l demo1 --name demo1 demo1/demo1:v1
fi

if [ "x$COMMAND" == "xstop" ]; then
    echo 'Stop docker image'
    docker kill demo1
fi

# TESTS
# venv/bin/python -m unittest discover -s ./tests -p 'test_*.py' -t . -b --locals -v

if [ "x$COMMAND" == "xdeploy" ]; then
    build
    echo Deploy docker image to the AWS
    echo I\'ll use account: $AWS_ACCOUNT \(like: 1234567.dkr.ecr.us-east-2.amazonaws.com\)
    echo AWS_PROFILE is $AWS_PROFILE
    echo AWS_REGION is $AWS_REGION
    aws ecr get-login-password --profile $AWS_PROFILE --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT
    docker_build 'demo1'
    docker tag demo1:latest $AWS_ACCOUNT/demo1:latest
    docker push $AWS_ACCOUNT/demo1:latest

    # Asyncio issue
    # https://forums.aws.amazon.com/thread.jspa?threadID=323670
    # Add a pseudo terminal in the Fargate Task definition (can only be added through Configure via JSON) with the following setting:
    # "pseudoTerminal": true
fi

if [ "x$COMMAND" == "xredeps" ]; then
    echo "Reinstall dependencies"
    .venv/bin/pip3 install -r requirements.txt
    .venv/bin/pip3 install -r requirements-tests.txt
    .venv/bin/pip3 install -r requirements-dev.txt
fi

if [ "x$COMMAND" == "xclean" ]; then
    echo "Clean temporary folders"
    find . -name __pycache__ | xargs rm -fr
fi

AVAILABLE_COMMANDS="build run stop deploy dev clean"
echo ''
[[ $AVAILABLE_COMMANDS =~ (^| )$COMMAND($| ) ]] && echo 'Ok' || echo 'Unknown command: ' "$COMMAND" && echo 'Available commands are: ' "$AVAILABLE_COMMANDS"

