# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/


service: fargate-dns-monitor

provider:
        name: aws
        runtime: nodejs12.x
        region: us-east-2
        iamRoleStatements:
                - Effect: "Allow"
                  Action:
                          - "ec2:DescribeNetworkInterfaces"
                          - "ecs:DescribeClusters"
                          - "ecs:ListTagsForResource"
                          - "route53:ChangeResourceRecordSets"
                  Resource: "*"


functions:
        registerPublicIp:
                memorySize: 128
                handler: src/update-task-dns.handler
                events:
                        - cloudwatchEvent:
                                event:
                                        source:
                                                - "aws.ecs"
                                        detail-type:
                                                - "ECS Task State Change"


package:
        exclude:
                - "**"
        include:
                - src/**
                - node_modules/**
                - "!node_modules/**/.serverless/**"
